data:
  train_files: data/grpo.yaml
  val_files: data/grpo.yaml
  data_folder: data/
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 4096
  max_response_length: 1024
  rollout_batch_size: 4
  shuffle: true
  seed: 1
  max_pixels: 100352
  min_pixels: 3136
  num_frames: 16

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 4
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 4
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 5.0e-7
      weight_decay: 1.0e-2
      strategy: adamw_bf16  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
      # warmup_style: cosine
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bf16
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 8
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    score_function: scripts/score_function.py:compute_score

trainer:
  total_episodes: 1
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math_grpo
  nnodes: 1